  name: "Exemplo pipeline"

  on:
    workflow_dispatch:

  jobs:
    estagio01:
      runs-on: ubuntu-latest
      steps:
        - name: Olá, Professor!
          run: echo "Olá, Professor!"
        - name: Sleep
          run: sleep 1
        - name: Olá, Aluno!
          run: echo "Olá, Aluno!"
    estagio02:
      needs: estagio01
      runs-on: ubuntu-latest
      steps:
        - name: "Sleep"
          run: sleep 5
    estagio03:
      needs: estagio02
      runs-on: ubuntu-latest
      steps:
        - name: "Sleep"
          run: sleep 2
    